#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

git config hooks.allownonascii true

# If there are whitespace errors, print the offending file names and fail.
# git diff-index --check --cached $against --

# *.lua check
luacheck=./luacheck/luacheck.exe #根据项目路径修改
luacheckCfgFilePath=./luacheck/.luacheckrc #根据项目路径修改
shouldRet=0
files=`git diff --cached --name-only --diff-filter=AMR $against` #add，modify，r
p=""
for f in $files; do
	if [ -z "$p" ]; then
		p=$f
	else
		p="$p $f"
	fi

	if [ -f "$p" ]; then
		if [ "${p##*.}" = "lua" ]; then
			if [[ $(uname) == "Darwin" ]]; then
				luacheck --config $luacheckCfgFilePath "$p"
				p=""
			elif [[ $(expr substr $(uname -s) 1 10) == "MINGW32_NT" ]] || [[ $(expr substr $(uname -s) 1 10) == "MINGW64_NT" ]] ; then
				$luacheck --config $luacheckCfgFilePath "$p"
				p=""
			fi
		fi

		ret="$?"
		if [[ $ret != 0 && $shouldRet == 0 ]]; then
			shouldRet=1
		fi
	fi
done

# asset and .meta check
ASSETS_DIR=game/Assets # Unity Assets Dir #根据项目路径修改
files=`git -c diff.renames=false diff --cached --name-only --diff-filter=A $against -- "$ASSETS_DIR"`
for f in $files; do
	ext="${f##*.}"
	base="${f%.*}"
	filename="$(basename "$f")"

	if [ "$ext" = "meta" ]; then
		if [ $(git ls-files --cached -- "$base" | wc -l) = 0 ]; then
cat <<EOF
Error: Redudant meta file.
Meta file \`$f' is added, but \`$base' is not in the git index.
Please add \`$base' to git as well.
EOF
			shouldRet=1
		fi
	elif [ "${filename##.*}" != '' ]; then
		p="$f"
		while [ "$p" != "$ASSETS_DIR" ]; do
			if [ $(git ls-files --cached -- "$p.meta" | wc -l) = 0 ]; then
cat <<EOF
Error: Missing meta file.
Asset \`$f' is added, but \`$p.meta' is not in the git index.
Please add \`$p.meta' to git as well.
EOF
				shouldRet=1
			fi
			p="${p%/*}"
		done
	fi
done

files=`git -c diff.renames=false diff --cached --name-only --diff-filter=D $against -- "$ASSETS_DIR"`
for f in $files; do
	ext="${f##*.}"
	base="${f%.*}"

	if [ "$ext" = "meta" ]; then
		if [ $(git ls-files --cached -- "$base" | wc -l) != 0 ]; then
cat <<EOF
Error: Missing meta file.
Meta file \`$f' is removed, but \`$base' is still in the git index.
Please revert the beta file or remove the asset file.
EOF
			shouldRet=1
		fi
	else
		p="$f"
		while [ "$p" != "$ASSETS_DIR" ]; do
			if [ $(git ls-files --cached -- "$p" | wc -l) = 0 ] && [ $(git ls-files --cached -- "$p.meta" | wc -l) != 0 ]; then
cat <<EOF
Error: Redudant meta file.
Asset \`$f' is removed, but \`$p.meta' is still in the git index.
Please remove \`$p.meta' from git as well.
EOF
				shouldRet=1
			fi
			p="${p%/*}"
		done
	fi
done

exit 1

if [ $shouldRet != 0 ]; then
	exit $shouldRet
fi